### ISSUE TITLE
Via Tender:   punch card

### ISSUE THREAD

**Issue by Kicksite-Support** [Kicksite-Support/HelpDesk#50]
Assigned to [Problems #1705](http://help.kicksite.net/discussions/problems/1705-punch-card). As reported in Tender:

<blockquote><p>Hi there, I'm trying to enter a 10 class card for Sam Krop for Krav Maga. When I click on attendance the (as opposed to 'date') nothing comes up for me in order for me to enter the number of classes. It used to come up when I clicked on "Attendance", but it's not coming up. Am I doing something wrong? Thank you! Sylvia (541)344-0404</p></blockquote>

**Comment by mindi286** [comment]
Hello Ma'am,

We would be happy to help you. We went ahead and added a Krav Maga punchcard membership for 10 classes to Samantha Krop. The same thing happened for us when we did it for you. We were able to save the membership and then go back in and edit it and add the 10 classes in for her. We apologize for this inconvenience and have let our programmers know about this. Please let us know if there is anything else we can do for you!

Kicksite Support

**Comment by mindi286** [comment]
Emailed Ross.

Memberships

Mindi Schwartz <mindi@kicksite.net>
Attachments8:33 PM (13 minutes ago)

to Ross 
Hey :) 

Soooooooo I just had a client email in saying that when they added a membership for someone it wouldn’t allow them to change between date and attendance. I tried it in dave’s and if you are editing a membership that already exists, it works perfectly fine. BUT if you add a new membership and then try to change between date and attendance, it doesn't give you the correct options for whichever one you choose. 
I have attached a screenshot. Please let me know if there is any further testing or questions. Thank you!!
